### ISSUE TITLE
Change report location

### ISSUE THREAD

**Issue by wkokolis** [Thatooine/go-test-html-report#4]
Is it possible to change the output location of the report?  The documentation doesn't say anything about it, but dumping the result to the root of the repo during testing is slightly problematic.  We have the following set up in our CI pipeline:

```
go-test-html-report -f ./gotest.log
```

When we archive the test report in Jenkins, it ends up archiving the entire repo, which means we're using far more space than necessary since everything is coming along for the ride.

If we could specify a target directory for the test report, that would solve the problem nicely.

Thanks,

**Comment by Thatooine** [comment]
Hey @wkokolis 

Am currently working on some code refactoring and simplification on the **fixes-updates** branch. I'll add the ability to specify a target output directory for the test reports. This will mostly like happen via a **- o** flag being added to the cli. All this should be done in 3+- days 

Thank you for your patience

**Comment by Thatooine** [comment]
Hey @wkokolis 

A new version (v1.1.0) of the **go-test-html-report** has been released and it should have the ability to provide a target directory for the test report. Please check it out when you  can. 

Regards,
